name: Label Issues as "To Do" once I create a new one
on:
  issues:
    types: [opened] #when a new issue is opened  the follwing code down below will be executed
permissions:
  issues: write  # Explicitly grants write permission to manage issues
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Label Issues as "To Do" once I create a new one
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} #we are validating this with github-token
          labels: "To Do"
